name: e_commerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
#-----Packages-----#
dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  #state managament
get: ^4.6.6

#-------Packages end------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/fonts/
  - assets/icons/
  - assets/images/
  - assets/logos/

fonts:
  - family:Poppins
  - fonts:
      - assets/fonts/Poppins/Poppins-Light.ttf
        weight:300
      - assets/fonts/Poppins/Poppins-Black.ttf
      - assets/fonts/Poppins/Poppins-Bold.ttf
      - assets/fonts/Poppins/Poppins-ExtraBold.ttf
      - assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight:600
      - assets/fonts/Poppins/Poppins-BlackItalic.ttf
      - assets/fonts/Poppins/Poppins-BoldItalic.ttf
      - assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
      - assets/fonts/Poppins/Poppins-Medium.ttf
        weight:500
      - assets/fonts/Poppins/Poppins-Regular.ttf
        weight:400
