name: e_commerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/fonts/
  - assets/icons/
  - assets/images/
  - assets/logos/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
      - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
      - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
      - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
